name: Rebuild
on:
  workflow_dispatch:
  push:
    branches:
      - new

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write
  deployments: write
  
concurrency:
  group: "pages"

jobs:
  rebuild:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
          
      - name: Checkout
        uses: actions/checkout@v6-beta
      
      - name: Rebuild
        run: |
         npm install
         npm run build
       
      - name: Upload built-dist
        uses: actions/upload-artifact@v5.0.0
        with:
          name: built-dist
          path: dist
      - name: Upload built-locales
        uses: actions/upload-artifact@v5.0.0
        with:
          name: built-locales
          path: locales
          
      - name: Checkout to new-builds
        uses: actions/checkout@v6-beta
        with:
          ref: new-builds
      
      - name: Clear out things
        run: |
          rm -rf dist/*
          rm -rf locales/*
          
      - name: Download built-dist
        uses: actions/download-artifact@v6.0.0
        with:
          name: built-dist
          path: dist/
      - name: Download built-locales
        uses: actions/download-artifact@v6.0.0
        with:
          name: built-locales
          path: locales/

      - name: debug
        run: |
          ls
      
      - name: Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: ${{ github.event.head_commit.message }}
          committer_name: GitHub Actions
          committer_email: actions@github.com
